# Generated by Django 3.2.23 on 2024-10-27 11:35

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end_coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('total_distance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fuel_stops', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('route_polyline', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['created_at'], name='route_plann_created_95c3af_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['state'], name='route_plann_state_a5d78a_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['retail_price'], name='route_plann_retail__63511e_idx'),
        ),
    ]
